name: Elixir CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1.16.0  
        env:
          ImageOS: ubuntu22
        with:
          elixir-version: "1.15.7" # Define the elixir version [required]
          otp-version: "26.0.2" # Define the OTP version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Compile
        run: MIX_ENV=test mix compile --warnings-as-errors
      - name: Run tests
        run: mix test
